### ISSUE TITLE
serialization/ deserialization is not robust enough

### ISSUE THREAD

**Issue by dit7ya** [KevinWang15/web-marker#12]
The current method relies on textBefore and textAfter properties and fails if they change. For example, if I create a highlight on any of the comments on the page https://news.ycombinator.com/item?id=28267975, the textBefore string would contain 'x minutes/hours ago' where the value of x will change later, making the entire process unstable. 

I think there needs to be a more robust approach to storing the highlight location.

Maybe some inspiration can be taken from - https://github.com/WorldBrain/Memex/blob/develop/src/highlighting/ui/highlight-dom-range.ts?

**Comment by KevinWang15** [comment]
I did my research, there are basically two ways to do range serialization / deserialization:

1. prefix, text, suffix
2. offset in page

Mainstream annotation software such as diigo and weava all use (1.), while Memex [supports both](https://github.com/WorldBrain/Memex/blob/6685579e7cae23ab8762d9cbbf195a875e4f38e2/src/highlighting/ui/anchoring/index.js#L30-L38), but now [defaults to 2](https://github.com/WorldBrain/Memex/blob/6685579e7cae23ab8762d9cbbf195a875e4f38e2/src/highlighting/ui/anchoring/index.js#L22).

Generally speaking I think 1. is the more robust way to go, because it is resistant to content changes.
With 2. , when there is any change to the content (user updating a post, "1 minute ago" becoming "10 minute ago"), there will be drifts to the highlight. 
Unless you are annotating static content that will never change (PDFs), or you have a snapshot mechanism built into the software, it's not recommended, the drifts may be huge after some time.

For 2. Memex is using https://github.com/tilgovi/dom-anchor-text-position

For 1., Memex is using https://github.com/tilgovi/dom-anchor-text-quote, a cool library that I never heard of before.

After digging into the algorithm of dom-anchor-text-quote, I did find some room for improvement:

a. If prefix + text + suffix match fails, we can try to use text + suffix match, prefix + text, or even just text match
b. https://github.com/google/diff-match-patch can be used to optimize text matching performance

I think a. is going to be enough to solve the case for hacker news (the user wouldn't highlight 'x minutes before', right?), I will implement it.

**Comment by KevinWang15** [comment]
I tried to fix this problem in https://github.com/notelix/web-marker/commit/88f71f29eddda95a81e9fe4391aa2bffd1a09439

Please try `@notelix/web-marker@1.0.10` to see if it is good

**Comment by dit7ya** [comment]
Thank you so much for doing the research and writing about it in detail. 

I tried the new version and it seems fine for the case I described. However, I still think there's more to do about it in future versions. Unfortunately it seems to me that there will always be some issues (due to the complexity of the modern web, it is not really a limitation on annotation libraries) with the intricate design of some pages and in that case maybe  a more verbose failure result might be useful - so that the users can be informed about what has changed and what can be done about the rotten highlight.

**Comment by KevinWang15** [comment]
Yes, there is no perfect algorithm for annotation deserialization, because the web is always changing.

In order to show a more verbose failure result and ask users what to do with the rotten highlight, you can actually catch the deserialization failure exception, and show a modal dialog.

Since everyone is using a different UI framework, what `web-marker` library can do is to throw an exception, and let the upstream system decide what to do with the exception. (I should probably use a custom exception class though, so that the upstream system can decode the exception with `instanceof`)

**Comment by KevinWang15** [comment]
Here is some demo code taken from https://github.com/notelix/notelix

It triggers deserialization on URL change, and retries failed deserialization with a backoff algorithm up to 10 times. It should be able to handle most of the cases.

```javascript
whenUrlChanges(() => {
    setTimeout(() => {
        loadAllAnnotationsData();
    });
});

let lastUrl;
function whenUrlChanges(callback) {
    setInterval(() => {
        const currentUrl = getNormalizedUrl();
        if (lastUrl !== currentUrl) {
            callback();
        }
        lastUrl = currentUrl;
    }, 500);
}

function getNormalizedUrl() {
    let href = window.location.href;
    let indexOfHash = href.indexOf("#");
    let indexOfQuestion = href.indexOf("?");
    if (indexOfHash > 0 && indexOfQuestion > 0 && indexOfHash < indexOfQuestion) {
        return href.substr(0, indexOfHash) + href.substr(indexOfQuestion);
    } else if (indexOfHash > 0) {
        return href.substr(0, indexOfHash);
    } else {
        return href;
    }
}

export function loadAllAnnotationsData() {
    let failureCount = 0;
    return queryAnnotationsByUrl(getNormalizedUrl()).then((list) => {
        list.map((item) => {
            state.annotations[item.uid] = item;

            try {
                marker.paint(state.annotations[item.uid]);
            } catch (e) {
                failureCount++;
                retryPaintMarker(0, item.uid);
            }
        });
    });
}

function retryPaintMarker(retryCount, uid) {
    setTimeout(() => {
        try {
            marker.paint(state.annotations[uid]);
        } catch (e) {
            if (retryCount < 10) {
                retryPaintMarker(retryCount + 1, uid);
            } else {
                // give up
                delete state.annotations[uid];
                // You can show a modal to inform users of the rotten highlight here
            }
        }
    }, (retryCount * 0.5 + 1) * (1 + Math.random()) * 1000);
}

```
